In [156]:
# Bu dökümantasyon'u kullanmak için Jupyter Notebook kullanmanızı tavsiye ederim. İlk açtığınız zaman ise Kernel-> Restart Kernell and Run All Cells
# işlemini uygulamanızı tavsiye ederim.

In [65]:
#conda install numpy ###normalde jupyter'e numpy bu kodla yüklenir. Ama bende bu kod hata verdiği için aşğaıdakini kullandım.

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np #burada numpy'ı import ettik. Kodlarımızda artık "np" ile numpy'ı kullanabileceğiz.

In [5]:
#numpy array

In [6]:
my_list = [10,20,30,40]

In [7]:
type(my_list)

list

In [9]:
np.array(my_list) #bu kod ile "my_list"'i çevirebiliyoruz.

array([10, 20, 30, 40])

In [10]:
my_numpy_array = np.array(my_list)

In [11]:
type(my_numpy_array)

numpy.ndarray

In [12]:
my_numpy_array

array([10, 20, 30, 40])

In [19]:
my_numpy_array[0] #bu ve alttaki örnekte index mantığı test ediliyor. Listelerde olduğu gibi buradada index ile istediğimiz değerlere ulaşabiliyoruz.

10

In [15]:
my_numpy_array[-1]

40

In [24]:
my_numpy_array[0] = 100 #burada 0. indexteki değeri değiştirdik. Numpy içindeki değerlerin değiştirilmesine izin veriyor.

In [22]:
my_numpy_array[0]

100

In [28]:
my_numpy_array.max()   # .max ile bu değerler arasından en büyük değeri istiyoruz.

100

In [29]:
my_numpy_array.min()  # .min ile bu değerler arasından en küçük değeri istiyoruz.

20

In [32]:
my_numpy_array.mean()   # .mean bu değerlerin ortalamasını alır.

47.5

In [33]:
matrix_list = [[1,0,0],[0,1,0],[0,0,1],[0,0,0]]

In [34]:
type(matrix_list)

list

In [36]:
matrix_list[0][0]

1

In [38]:
numpy_matrix_list = np.array(matrix_list)

In [39]:
numpy_matrix_list

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0]])

In [41]:
numpy_matrix_list[0][0]

1

In [43]:
numpy_matrix_list.shape # bu kod matrixin 4 row 3 column'dan oluştuğunu gösteriyor. 

(4, 3)

In [44]:
#arange

In [45]:
range(0,10)

range(0, 10)

In [53]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [50]:
np.arange(0,10)   # arange = range'in numpy versiyonu

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
np.arange(0,30,2)  # bu örnekte 0'dan 30'a kadar ikişer ikişer gitmesini istedik.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [56]:
np.zeros(10)     #bazen numpy'da 0dan oluşan değerlere ihtiyaç duyulabiliyor. Bu komut parantezin içindeki sayı kadar 0 oluşturuyor.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [58]:
np.zeros((10,10)) #bu kod 10'a 10 her şeyi sıfır olan matrix oluşturuyor.

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [60]:
np.ones((10,10)) #bir önceki örnekteki .zeros'un 1li versiyonu

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [61]:
#linspace

In [64]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [66]:
#random

In [70]:
np.random.randint(1,10,3) #bu kod ile 1'den 10'a kadar rastgele bir değer istiyoruz.Parantezin sonunda 3 olduğu için 3 farklı değer veriyor.

array([9, 3, 5])

In [71]:
np.random.randint(1,100)

52

In [72]:
np.random.randint(1,100,10)

array([33, 75,  1, 75, 91, 51, 55, 58, 49, 92])

In [73]:
#numpy arrays methods

In [74]:
my_numpy_list = np.arange(0,20)

In [75]:
my_numpy_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [76]:
my_numpy_list[4]

4

In [77]:
my_numpy_list[4:9]

array([4, 5, 6, 7, 8])

In [78]:
my_numpy_list[4:9:2]

array([4, 6, 8])

In [79]:
my_list = list(range(0,20))

In [80]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [81]:
my_list[4:9:2]

[4, 6, 8]

In [84]:
#my_list[4:9] = -10  ###bu örnekte görüldüğü gibi listeler indexler arası değeri alıp başka bir değere eşitlemeyi desteklemiyor. Kod hata veriyor.

In [87]:
my_numpy_list[4:9] = -10 #numpy'da ise bu işlemi yapabiliyoruz. 4 ve 9. bu örnekte index arasındaki tüm değerler -10'a eşitlendi.

In [86]:
my_numpy_list

array([  0,   1,   2,   3, -10, -10, -10, -10, -10,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [88]:
other_list = np.arange(0,15) 

In [89]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
other_list[4:10]

array([4, 5, 6, 7, 8, 9])

In [91]:
slicing_list = other_list[4:10]

In [92]:
slicing_list

array([4, 5, 6, 7, 8, 9])

In [93]:
other_list

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [94]:
slicing_list[0]

4

In [95]:
slicing_list[:] = 100

In [96]:
slicing_list

array([100, 100, 100, 100, 100, 100])

In [ ]:
other_list #biz slicing_list'i other listin bazı elemanlarını kullanarak tanımlayıp üzerinde değişiklikler yaptık. Normalde bu değişiklikler 
#other_list'i etkilemezdi. Ancak numpy'da ise slicing_list üzerinde yaptığımız değişiklikler other_list üzerindende yapıldı. Kısacası other_list'ide
#düzenlemiş olduk.

In [103]:
my_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [105]:
slicing_my_list = my_list[4:9]

In [106]:
slicing_my_list

[4, 5, 6, 7, 8]

In [108]:
slicing_my_list[0] = -100

In [109]:
slicing_my_list[1] = -100

In [110]:
slicing_my_list

[-100, -100, 6, 7, 8]

In [113]:
my_list #görüldüğü gibi listeler üzerinde çalıştığımızda herhangi bir şey değişmemiş. slicing_list üzerindeki değişiklikler sadece kendisini etkilemiş.

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [114]:
numpy_list_3 = np.arange(0,20)

In [115]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [128]:
numpy_list_3_copy = numpy_list_3.copy() #burada numpy_list_3'ün kopyasını alıyoruz. Böylelikle slicing_3 üzerinde yapılan değişiklikler sadece copy'i
#etkileyecek asıl numpy_list_3 üzerinde bir değişiklik olmayacak. 

In [118]:
numpy_list_3_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [120]:
slicing_3 = numpy_list_3_copy[4:9]

In [121]:
slicing_3[:] = -100

In [122]:
slicing_3

array([-100, -100, -100, -100, -100])

In [123]:
numpy_list_3_copy

array([   0,    1,    2,    3, -100, -100, -100, -100, -100,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19])

In [124]:
numpy_list_3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [129]:
# numpy operations with numpy arrays

In [131]:
new_array = np.random.randint(1,150,25) # 1 den 150'ye kadar 25 tane rastgele sayı vericek.

In [132]:
new_array

array([ 97,  54,  29,  95,  26,  25, 101,  46, 115,  13, 108, 112, 139,
        28, 123, 141,  96, 108, 118,  73, 116,  96, 114, 148, 141])

In [133]:
new_array > 50 #bu kodla değerler arasından 50'den büyük olanları tespit ediyorsun.

array([ True,  True, False,  True, False, False,  True, False,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [134]:
result_array = new_array > 50 

In [137]:
result_array

array([ True,  True, False,  True, False, False,  True, False,  True,
       False,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [138]:
new_array

array([ 97,  54,  29,  95,  26,  25, 101,  46, 115,  13, 108, 112, 139,
        28, 123, 141,  96, 108, 118,  73, 116,  96, 114, 148, 141])

In [139]:
new_array[result_array]

array([ 97,  54,  95, 101, 115, 108, 112, 139, 123, 141,  96, 108, 118,
        73, 116,  96, 114, 148, 141])

In [140]:
last_array = np.arange(0,30)

In [141]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [143]:
last_array + last_array #normalde yan yana yazardı ama numpy kütüphanesinde gerçekten topluyor.

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58])

In [146]:
last_array * last_array #buradada gerçekten çarptı

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625,
       676, 729, 784, 841])

In [147]:
last_array - last_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0])

In [158]:
last_array / last_array # ilk işlem 0/0 olduğu için hata veriyor ama sonrasındaki işlemleri yerine getiriyor.

C:\Users\ahmed\AppData\Local\Temp\ipykernel_4708\294271750.py:1: RuntimeWarning: invalid value encountered in divide
  last_array / last_array # ilk işlem 0/0 olduğu için hata veriyor ama sonrasındaki işlemleri yerine getiriyor.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.])

In [149]:
last_array.max()

29

In [150]:
last_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [152]:
np.max(last_array)

29

In [153]:
np.mean(last_array)

14.5

In [155]:
np.sqrt(last_array) # .sqrt = karekökünü alma işlemi.

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
       5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481])